"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from ._core import *
from ._email import *
from ._martor import *
from ._tinymce import *
from ._celery import *
from ._ipware import IPWARE_META_PRECEDENCE_ORDER
from ._logging import LOGGING
