"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .django._core import *
from .django._email import *
from .django._logging import LOGGING
from .apps._martor import *
from .apps._tinymce import *
from .apps._celery import *
from .apps._ipware import IPWARE_META_PRECEDENCE_ORDER
from .apps._gravatar import *
from .apps._notifications import *
