# Generated by Django 2.0.1 on 2018-07-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0019_auto_20180629_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='requester',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideax.Challenge'),
        ),
    ]
