# Generated by Django 2.0.1 on 2018-08-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0020_auto_20180705_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='ideax.UserProfile'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_author', to='ideax.UserProfile'),
        ),        
    ]
