# Generated by Django 2.0.1 on 2018-08-16 19:25

from django.db import migrations


def foward(apps, schema_editor):
    UserProfile = apps.get_model("ideax", "UserProfile")
    Idea = apps.get_model("ideax", "Idea")
    for idea in Idea.objects.all():
        idea.authors.add(idea.author)


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0021_auto_20180816_1616'),
    ]

    operations = [
        migrations.RunPython(foward)
    ]
