# Generated by Django 2.0.9 on 2018-10-22 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0023_auto_20181022_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
