# Generated by Django 2.0.9 on 2018-10-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0023_auto_20181022_1359'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='init_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='use_term',
            name='final_date',
            field=models.DateTimeField(),
        ),
    ]
