# Generated by Django 2.0.9 on 2018-10-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0024_auto_20181022_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='init_date',
        ),
    ]
