# Generated by Django 2.0.9 on 2018-10-22 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0025_remove_challenge_init_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
